### ISSUE TITLE
Weird behavior with the default match operator

### ISSUE THREAD

**Issue by JGailor** [santinic/pampy#23]
```
>>> from pampy import match, _

>>> _
_


>>> def matcher(val):
...     return match(val, int, "int", _, "something else",)

>>> matcher("hi")
'something else'


>>> matcher(1)
'int'


>>> matcher("hi")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in matcher
  File "/usr/local/lib/python3.7/site-packages/pampy/pampy.py", line 186, in match
    raise MatchError("'_' not provided. This case is not handled:\n%s" % str(var))
pampy.pampy.MatchError: '_' not provided. This case is not handled:
hi

'_' not provided. This case is not handled:
hi
```

**Comment by santinic** [comment]
Weird, this doesn't happen in scripts. I think it's an artifact of python shells, because you call "_" before using it. I really don't know why.

**Comment by catethos** [comment]
I think this is due to a bug in ipython: ipython/ipython#11325
